version: '2'
services:
  app:
    image: openresty/openresty:buster-fat
    container_name: nginx
    restart: always
    network_mode: host
    ports:
      - "8888:8888"
    volumes:
      - "./certs/:/etc/nginx/certs/"
      - "./conf/:/etc/nginx/conf.d/"
      - "./static/:/usr/local/openresty/nginx/html/"
      - "./logs:/usr/local/openresty/nginx/logs"   
    